# --------- CHOOSE ONE
use_heatmap: False
use_descriptor_tracks: True
# ----------

# If use_descriptor_tracks...
num_reference_descriptors: 9
display_all_separate_windows: False
#

norm_diff_threshold: 0.25
heatmap_vis_upper_bound: 0.75
blend_weight_original_image: 0.3
randomize_images: True
publish_to_ros: False
frame_skip: 5

# -------------------------------------------
num_camera_target: 1
# -------------------------------------------

networks:
#- "imitation/sugar_spatial_3"
#- "imitation/real_shoe_spatial_3"
# - "imitation/real_many_shoes_spatial_3"
# - "imitation/real_many_shoes_corl_3"
#- "sugar_box_3"
  - "push_box_spatial_3"
kernel_variance: 1.0