train:
  random_seed: 42
  n_epoch: 1000
  lr: 0.0001
  adam_beta1: 0.9
  batch_size: 1
  num_workers: 12
  train_valid_ratio: 0.9
  log_per_iter: 10
  ckp_per_iter: 5000
  resume_epoch: -1
  resume_iter: -1

dataset:
  sample_matches_only_off_mask: True
  N_matches: 150
  N_masked_non_matches: 150
  N_background_non_matches: 100

network:
  descriptor_dimension: 3
  compute_best_match_with: "min_l2"

loss_function:
 type: "heatmap_l2"
 sigma: 5.0
 heatmap_type: "exp" # ['exp', 'softmax']

