train:
  random_seed: 1
  n_epoch: 50
  lr: 0.0001
  lr_scheduler_patience: 10
  lr_scheduler_factor: 0.9
  adam_beta1: 0.9
  batch_size: 2
  num_workers: 20
  train_valid_ratio: 0.9
  log_per_iter: 10
  ckp_per_iter: 5000
  resume_epoch: -1
  resume_iter: -1

dataset:
  sample_matches_only_off_mask: True
  N_matches: 50
  N_masked_non_matches: 150
  N_background_non_matches: 100
  normalization: "ImageNet" # ["ImageNet", "DON"]
  epoch_size:
    train: 10000 # set it to -1 if you don't want it
    valid: 1000
  camera_names: [] # empty list
  data_augmentation: False

network:
  descriptor_dimension: 3
  compute_best_match_with: "min_l2"
  sigma_descriptor_heatmap: 5 # the sigma used to create heatmap from descriptor image
  backbone: "fcn_resnet50"
  pretrained: False

loss_function:
  heatmap:
    enabled: True
    weight: 1.0
    type: "heatmap_l2"
    sigma_fraction: 0.00625
    heatmap_type: "exp" # ['exp', 'softmax']
  spatial_expectation:
    enabled: True
    weight: 1.0
  depth_3d:
    enabled: True
    weight: 1.0


